[package]
name = "gladoid-bevy"
version = "0.1.0"
edition = "2021"


[dependencies]
pyo3 = { version = "0.20.3", features = ["auto-initialize", "anyhow"] }
bevy_ecs = "^0.13"
rand = "0.8.5"
anyhow = "1.0.81"
log = "0.4.21"
env_logger = "0.11.3"
