version: '3.4'

volumes:
  debug-py:

services:
  gladoidbot:
    image: gladoidbot
    build:
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./src:/app/gladoid-bevy/src
      - ./Cargo.toml:/app/gladoid-bevy/Cargo.toml
      - ./Cargo.lock:/app/gladoid-bevy/Cargo.lock
    command: cargo watch --poll --why -x run
