from typing import overload

class Player:
    id: int
    name: str

class GladoidGameWorld:
    @overload
    def insert_action(self, action_id: int, player_id: int) -> None: ...
    @overload
    def insert_action(self, action_id: int, weapon_id: int) -> None: ...
    @overload
    def insert_action(self, action_id: int) -> None: ...
    def tick(self) -> None: ...
    def check_need_action(self) -> bool: ...
    def get_players(self) -> list[Player]: ...

def create_world() -> GladoidGameWorld: ...
