[tool.poetry]
name = "gladoid-bevy"
version = "0.1.0"
description = ""
authors = ["Sergen Pekşen <peksensergen@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.3.2"
